version: '3.1'
services:
  mongo:
    image: mongo:3.6
    build: ./
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./conf/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - /data/data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: jimimongo@123456
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8077:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: jimimongo@123456
