version: '3'

services:
  redistest:
    image: redis:3.2
    container_name: redistest
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - net_db
    volumes:
      - ./redis.conf:/etc/redis/redis.conf:rw
      - /data/data/redistest:/data:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes

networks:
  net_db:
    driver: bridge
