version: '3.5'
services:
  mycat-server:
    image: longhronshens/mycat-docker
    container_name: mycat
    ports:
      - 8066:8066
    volumes:
      - /home/mycat/server.xml:/usr/local/mycat/conf/server.xml
      - /home/mycat/rule.xml:/usr/local/mycat/conf/rule.xml
      - /home/mycat/schema.xml:/usr/local/mycat/conf/schema.xml
