version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: elasticsearch
    environment:
      - cluster.name=escluster4docker
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data1/data/esdocker/data:/usr/share/elasticsearch/data
      - /data1/data/esdocker/logs:/usr/share/elasticsearch/logs
    ports:
      - 9600:9200
      - 9700:9300
#volumes:
#  data01:
#    driver: local

