version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper   ## 镜像
    container_name: zookeeper
    ports:
      - "2181:2181"                 ## 对外暴露的端口号
    restart: always
  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.3       ## 镜像
    container_name: kafka
    volumes: 
        - /etc/localtime:/etc/localtime ## 挂载位置（kafka镜像和宿主机器之间时间保持一直）
        - /data/data/kafka/logs:/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.21.142   ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: 172.18.21.142:2181       ## 卡夫卡运行是基于zookeeper的
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_DELETE_RETENTION_MS: 1000
    depends_on:
      - zookeeper
    restart: always
#  kafka-managertest:  
#    image: sheepkiller/kafka-manager                ## 镜像：开源的web管理kafka集群的界面
#    container_name: kafka-managertest
#    environment:
#        ZK_HOSTS: 10.10.86.6                   ## 修改:宿主机IP
#    ports:  
#      - "9001:9000"                                 ## 暴露端口
